Algoritmo "014-MULTIPLO_DE_10"

// Descrição   : Faça um programa que leia um número
// inteiro qualquer e verifique se ele é múltiplo de 10.

Var
   // Seção de Declarações das variáveis
   NUMERO:INTEIRO

Inicio

   ESCREVAL("DIGITE UM NÚMERO INTEIRO")
   LEIA(NUMERO)
   SE(NUMERO%10=0) ENTAO
      ESCREVAL("O NÚMERO DIGITADO É MÚLTIPLO DE 10")
   SENAO
      ESCREVAL("NÃO É MÚLTIPLO DE 10")
   FIMSE
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo